### ISSUE TITLE
Wardrobe not opening error

### ISSUE THREAD

**Issue by enesright** [JericoFX/jk-helper#1]
Normally this event works when I use it elsewhere, but it did not work in this part of jk-helper.

![image](https://github.com/user-attachments/assets/ac2209dd-e8b6-4133-8b43-39dba798a9cb)

![image](https://github.com/user-attachments/assets/fa040273-b051-4786-a504-a42843df6c75)

![image](https://github.com/user-attachments/assets/0a9e5bab-95ee-405c-8351-aeba676b0ef2)

**Comment by JericoFX** [comment]
can you tell me if you restarted the script? or maybe print the line 61 print(self.data.job,typeZone) so you can check wich one is nil

**Comment by enesright** [comment]
I printed but no print came

**Comment by JericoFX** [comment]
you need to put the print in before the line 61

**Comment by enesright** [comment]
![image](https://github.com/user-attachments/assets/6073d642-4813-4a4f-a99d-38d0dbe95d4c)

**Comment by JericoFX** [comment]
is not detecting your job name

**Comment by enesright** [comment]
I didn't change job name, it's still for testing purposes as you arranged.

**Comment by JericoFX** [comment]
can you test now?, i forgot to add the job in the parameters

**Comment by enesright** [comment]
When I try to open it doesn't open and there is no error

**Comment by enesright** [comment]
When I try to open it doesn't open and there is no error
